# Importing Libraries

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving listings.csv to listings.csv

In [ ]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.3-cp310-cp310-manylinux2014_x86_64.whl (98.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 8.4 MB/s eta 0:00:00
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.25.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.50.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)
Installing collected packages: catboost
Successfully installed catboost-1.2.3

In [ ]:
import warnings
warnings.simplefilter('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import  LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, KFold
from sklearn import metrics
from sklearn.linear_model import LinearRegression

# Importing Data

In [ ]:
df = pd.read_csv(r"listings.csv")

# Data Exploration

In [ ]:
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,24018771,https://www.airbnb.com/rooms/24018771,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.74 · 1 bedroom · 1 bed · ...,NaN,NaN,https://a0.muscache.com/pictures/1030ee76-f3f7...,179038571,...,4.78,4.77,4.72,STR-2009-FDSXPB,f,3,0,3,0,1.83
1,50680103,https://www.airbnb.com/rooms/50680103,20240108030557,2024-01-08,city scrape,Boat in Toronto · 1 bedroom · 1 bath,NaN,NaN,https://a0.muscache.com/pictures/91f84c43-e010...,396389036,...,NaN,NaN,NaN,Exempt,t,1,1,0,0,NaN
2,1018845223985730763,https://www.airbnb.com/rooms/1018845223985730763,20240108030557,2024-01-08,city scrape,Townhouse in Toronto · ★New · 1 bedroom · 1 be...,NaN,NaN,https://a0.muscache.com/pictures/f1e047ed-949d...,9660032,...,NaN,NaN,NaN,NaN,t,4,1,3,0,NaN
3,842991103042611460,https://www.airbnb.com/rooms/842991103042611460,20240108030557,2024-01-08,city scrape,Bed and breakfast in Toronto · ★4.67 · 1 bedro...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,128444795,...,5.00,5.00,5.00,STR-2011-GTCKVH,f,1,0,1,0,0.51
4,1004965626999219484,https://www.airbnb.com/rooms/1004965626999219484,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.73 · 1 bedroom · 4 beds ·...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,120551336,...,5.00,4.93,4.80,STR-2310-GYFHHV,f,1,0,1,0,6.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20381,43740738,https://www.airbnb.com/rooms/43740738,20240108030557,2024-01-09,city scrape,Condo in Toronto · ★4.88 · 1 bedroom · 1 bed ·...,NaN,Celebrities and Professional Athletes Frequent...,https://a0.muscache.com/pictures/ceccecfc-e2a4...,349513985,...,4.93,4.90,4.76,STR-2209-JDQDVM,f,1,0,1,0,3.33
20382,14694749,https://www.airbnb.com/rooms/14694749,20240108030557,2024-01-09,city scrape,Rental unit in Toronto · ★4.92 · 1 bedroom · 1...,NaN,Brockton Village is a great mixed neighbourhoo...,https://a0.muscache.com/pictures/dbfdcd95-f0f0...,91382765,...,4.98,4.85,4.87,STR-2010-FGHDPB,t,1,0,1,0,3.32
20383,955162189200947880,https://www.airbnb.com/rooms/955162189200947880,20240108030557,2024-01-09,city scrape,Townhouse in Toronto · ★5.0 · 4 bedrooms · 5 b...,NaN,"Walking distance of shops, parks, and restaura...",https://a0.muscache.com/pictures/miso/Hosting-...,531113660,...,5.00,5.00,5.00,STR-2303-GZXRVV,t,1,1,0,0,1.81
20384,894406870652307040,https://www.airbnb.com/rooms/894406870652307040,20240108030557,2024-01-09,city scrape,Rental unit in Toronto · ★4.51 · 2 bedrooms · ...,NaN,"Welcome to Toronto Cityplace, a place to live ...",https://a0.muscache.com/pictures/miso/Hosting-...,514941841,...,4.54,4.73,4.32,STR-2305-HRKVHX,f,1,1,0,0,5.05
20385,616449374883279574,https://www.airbnb.com/rooms/616449374883279574,20240108030557,2024-01-09,city scrape,Condo in Toronto · ★4.96 · 1 bedroom · 1 bed ·...,NaN,"Amazing location 500m from CN Tower, 450m from...",https://a0.muscache.com/pictures/miso/Hosting-...,158368655,...,4.98,4.98,4.83,STR-2202-GZFDVH,t,1,0,1,0,4.90

In [ ]:
df.shape

(20386, 75)

In [ ]:
df.head(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,24018771,https://www.airbnb.com/rooms/24018771,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.74 · 1 bedroom · 1 bed · ...,NaN,NaN,https://a0.muscache.com/pictures/1030ee76-f3f7...,179038571,...,4.78,4.77,4.72,STR-2009-FDSXPB,f,3,0,3,0,1.83
1,50680103,https://www.airbnb.com/rooms/50680103,20240108030557,2024-01-08,city scrape,Boat in Toronto · 1 bedroom · 1 bath,NaN,NaN,https://a0.muscache.com/pictures/91f84c43-e010...,396389036,...,NaN,NaN,NaN,Exempt,t,1,1,0,0,NaN
2,1018845223985730763,https://www.airbnb.com/rooms/1018845223985730763,20240108030557,2024-01-08,city scrape,Townhouse in Toronto · ★New · 1 bedroom · 1 be...,NaN,NaN,https://a0.muscache.com/pictures/f1e047ed-949d...,9660032,...,NaN,NaN,NaN,NaN,t,4,1,3,0,NaN
3,842991103042611460,https://www.airbnb.com/rooms/842991103042611460,20240108030557,2024-01-08,city scrape,Bed and breakfast in Toronto · ★4.67 · 1 bedro...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,128444795,...,5.00,5.00,5.00,STR-2011-GTCKVH,f,1,0,1,0,0.51
4,1004965626999219484,https://www.airbnb.com/rooms/1004965626999219484,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.73 · 1 bedroom · 4 beds ·...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,120551336,...,5.00,4.93,4.80,STR-2310-GYFHHV,f,1,0,1,0,6.92
5,924249347864823562,https://www.airbnb.com/rooms/924249347864823562,20240108030557,2024-01-08,city scrape,Home in Scarborough · ★5.0 · 1 bedroom · 1 bed...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,224870607,...,5.00,4.67,4.67,NaN,t,11,0,11,0,0.49
6,51907095,https://www.airbnb.com/rooms/51907095,20240108030557,2024-01-08,city scrape,Home in Toronto · ★5.0 · 1 bedroom · 1 bed · 1...,NaN,NaN,https://a0.muscache.com/pictures/d94332b7-fa54...,224870607,...,5.00,4.43,4.57,NaN,f,11,0,11,0,0.25
7,831216233852987034,https://www.airbnb.com/rooms/831216233852987034,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.67 · 1 bedroom · 1 bed · ...,NaN,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,82569874,...,5.00,4.33,4.33,NaN,f,10,1,9,0,0.67
8,763116487116827873,https://www.airbnb.com/rooms/763116487116827873,20240108030557,2024-01-08,city scrape,Home in Toronto · 1 bedroom · 1 bed · 1.5 baths,NaN,It is at a peaceful neighborhood and family fr...,https://a0.muscache.com/pictures/miso/Hosting-...,137701267,...,5.00,5.00,5.00,STR-2306-FRWRVQ,f,5,0,5,0,0.11
9,14016370,https://www.airbnb.com/rooms/14016370,20240108030557,2024-01-08,city scrape,Home in Toronto · ★4.59 · 1 bedroom · 1 bed · ...,NaN,NaN,https://a0.muscache.com/pictures/0d4b8f7d-d823...,22735639,...,4.89,4.58,4.73,NaN,f,2,0,2,0,0.30

Warning: Total number of columns (75) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [ ]:
df.describe()

,id,scrape_id,description,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,2.038600e+04,2.038600e+04,0.0,2.038600e+04,20384.000000,20384.000000,0.0,20386.000000,20386.000000,20386.000000,...,15131.000000,15128.000000,15129.000000,15127.000000,15129.000000,20386.000000,20386.000000,20386.000000,20386.000000,15128.000000
mean,4.354224e+17,2.024011e+13,NaN,1.995578e+08,7.803817,13.628238,NaN,43.684573,-79.397822,3.135534,...,4.726527,4.850878,4.862691,4.825327,4.687249,4.501423,2.652409,1.810360,0.038556,1.339291
std,4.444135e+17,0.000000e+00,NaN,1.864795e+08,38.861606,99.944890,NaN,0.049984,0.071624,2.015716,...,0.449963,0.345281,0.354306,0.310157,0.440704,9.532091,8.203264,4.831722,0.397422,1.677490
min,1.419000e+03,2.024011e+13,NaN,1.565000e+03,1.000000,1.000000,NaN,43.585750,-79.623950,1.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.807186e+07,2.024011e+13,NaN,3.401644e+07,1.000000,1.000000,NaN,43.646403,-79.430467,2.000000,...,4.670000,4.840000,4.870000,4.780000,4.610000,1.000000,0.000000,0.000000,0.000000,0.200000
50%,5.493063e+17,2.024011e+13,NaN,1.340972e+08,2.000000,3.000000,NaN,43.665750,-79.397817,2.000000,...,4.870000,4.960000,4.980000,4.920000,4.790000,1.000000,1.000000,0.000000,0.000000,0.625000
75%,8.913686e+17,2.024011e+13,NaN,3.643726e+08,4.000000,7.000000,NaN,43.711700,-79.372003,4.000000,...,5.000000,5.000000,5.000000,5.000000,4.950000,3.000000,1.000000,2.000000,0.000000,1.940000
max,1.063309e+18,2.024011e+13,NaN,5.548931e+08,2260.000000,8875.000000,NaN,43.838414,-79.128010,16.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,95.000000,95.000000,46.000000,8.000000,12.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20386 entries, 0 to 20385
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            20386 non-null  int64
 1   listing_url                                   20386 non-null  object
 2   scrape_id                                     20386 non-null  int64
 3   last_scraped                                  20386 non-null  object
 4   source                                        20386 non-null  object
 5   name                                          20386 non-null  object
 6   description                                   0 non-null      float64
 7   neighborhood_overview                         11337 non-null  object
 8   picture_url                                   20386 non-null  object
 9   host_id                                       20386 non-null  int64
 10  host_url                                      20386 non-null  object
 11  host_name                                     20384 non-null  object
 12  host_since                                    20384 non-null  object
 13  host_location                                 15288 non-null  object
 14  host_about                                    9703 non-null   object
 15  host_response_time                            13654 non-null  object
 16  host_response_rate                            13654 non-null  object
 17  host_acceptance_rate                          14961 non-null  object
 18  host_is_superhost                             20159 non-null  object
 19  host_thumbnail_url                            20384 non-null  object
 20  host_picture_url                              20384 non-null  object
 21  host_neighbourhood                            8567 non-null   object
 22  host_listings_count                           20384 non-null  float64
 23  host_total_listings_count                     20384 non-null  float64
 24  host_verifications                            20386 non-null  object
 25  host_has_profile_pic                          20384 non-null  object
 26  host_identity_verified                        20384 non-null  object
 27  neighbourhood                                 11338 non-null  object
 28  neighbourhood_cleansed                        20386 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      20386 non-null  float64
 31  longitude                                     20386 non-null  float64
 32  property_type                                 20386 non-null  object
 33  room_type                                     20386 non-null  object
 34  accommodates                                  20386 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                20378 non-null  object
 37  bedrooms                                      4 non-null      float64
 38  beds                                          19890 non-null  float64
 39  amenities                                     20386 non-null  object
 40  price                                         16595 non-null  object
 41  minimum_nights                                20386 non-null  int64
 42  maximum_nights                                20386 non-null  int64
 43  minimum_minimum_nights                        20386 non-null  int64
 44  maximum_minimum_nights                        20386 non-null  int64
 45  minimum_maximum_nights                        20386 non-null  int64
 46  maximum_maximum_nights                        20386 non-null  int64
 47  minimum_nights_avg_ntm                        20386 non-null  float64
 48  maximum_nights_avg_ntm                        20386 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              16595 non-null  object
 51  availability_30                               20386 non-null  int64
 52  availability_60                               20386 non-null  int64
 53  availability_90                               20386 non-null  int64
 54  availability_365                              20386 non-null  int64
 55  calendar_last_scraped                         20386 non-null  object
 56  number_of_reviews                             20386 non-null  int64
 57  number_of_reviews_ltm                         20386 non-null  int64
 58  number_of_reviews_l30d                        20386 non-null  int64
 59  first_review                                  15128 non-null  object
 60  last_review                                   15128 non-null  object
 61  review_scores_rating                          15132 non-null  float64
 62  review_scores_accuracy                        15129 non-null  float64
 63  review_scores_cleanliness                     15131 non-null  float64
 64  review_scores_checkin                         15128 non-null  float64
 65  review_scores_communication                   15129 non-null  float64
 66  review_scores_location                        15127 non-null  float64
 67  review_scores_value                           15129 non-null  float64
 68  license                                       9456 non-null   object
 69  instant_bookable                              20386 non-null  object
 70  calculated_host_listings_count                20386 non-null  int64
 71  calculated_host_listings_count_entire_homes   20386 non-null  int64
 72  calculated_host_listings_count_private_rooms  20386 non-null  int64
 73  calculated_host_listings_count_shared_rooms   20386 non-null  int64
 74  reviews_per_month                             15128 non-null  float64
dtypes: float64(20), int64(21), object(34)
memory usage: 11.7+ MB

In [ ]:
df.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 75, dtype: object

In [ ]:
df.isnull().sum()

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
source                                             0
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               5258
Length: 75, dtype: int64

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = pd.read_csv(r"listings.csv")
# Drop columns that might not be useful for prediction
data.drop(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'amenities', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms'], axis=1, inplace=True)

# Handling missing values
data['price'] = data['price'].replace('[\$,]', '', regex=True).astype(float)
data['price'].fillna(data['price'].median(), inplace=True)
data['reviews_per_month'].fillna(0, inplace=True)


# Encode categorical variables
data = pd.get_dummies(data, columns=['property_type', 'room_type'])

# Split the dataset into features and target variable
X = data.drop('price', axis=1)
y = data['price']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.dropna(inplace=True)
y_train = y_train[X_train.index]

# Drop rows with missing values from X_test and y_test
X_test.dropna(inplace=True)
y_test = y_test[X_test.index]


# Initialize and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 41964.842338690476

In [ ]:
data.columns

Index(['accommodates', 'beds', 'price', 'minimum_nights', 'maximum_nights',
       'number_of_reviews', 'reviews_per_month', 'property_type_Boat',
       'property_type_Camper/RV', 'property_type_Casa particular',
       'property_type_Castle', 'property_type_Earthen home',
       'property_type_Entire bungalow', 'property_type_Entire condo',
       'property_type_Entire cottage', 'property_type_Entire guest suite',
       'property_type_Entire guesthouse', 'property_type_Entire home',
       'property_type_Entire home/apt', 'property_type_Entire loft',
       'property_type_Entire place', 'property_type_Entire rental unit',
       'property_type_Entire serviced apartment',
       'property_type_Entire townhouse', 'property_type_Entire vacation home',
       'property_type_Entire villa', 'property_type_Floor',
       'property_type_Island', 'property_type_Private room',
       'property_type_Private room in barn',
       'property_type_Private room in bed and breakfast',
       'property_type_Private room in bungalow',
       'property_type_Private room in casa particular',
       'property_type_Private room in castle',
       'property_type_Private room in condo',
       'property_type_Private room in cottage',
       'property_type_Private room in earthen home',
       'property_type_Private room in floor',
       'property_type_Private room in guest suite',
       'property_type_Private room in guesthouse',
       'property_type_Private room in home',
       'property_type_Private room in hostel',
       'property_type_Private room in hut',
       'property_type_Private room in loft',
       'property_type_Private room in minsu',
       'property_type_Private room in rental unit',
       'property_type_Private room in serviced apartment',
       'property_type_Private room in tiny home',
       'property_type_Private room in townhouse',
       'property_type_Private room in treehouse',
       'property_type_Private room in vacation home',
       'property_type_Private room in villa',
       'property_type_Room in aparthotel',
       'property_type_Room in bed and breakfast',
       'property_type_Room in boutique hotel', 'property_type_Room in hotel',
       'property_type_Shared room',
       'property_type_Shared room in bed and breakfast',
       'property_type_Shared room in boat',
       'property_type_Shared room in bungalow',
       'property_type_Shared room in casa particular',
       'property_type_Shared room in condo',
       'property_type_Shared room in guest suite',
       'property_type_Shared room in guesthouse',
       'property_type_Shared room in home',
       'property_type_Shared room in hostel',
       'property_type_Shared room in hotel',
       'property_type_Shared room in loft',
       'property_type_Shared room in rental unit',
       'property_type_Shared room in townhouse',
       'property_type_Shipping container', 'property_type_Tiny home',
       'room_type_Entire home/apt', 'room_type_Hotel room',
       'room_type_Private room', 'room_type_Shared room'],
      dtype='object')

In [ ]:
X_train

,accommodates,beds,minimum_nights,maximum_nights,number_of_reviews,reviews_per_month,property_type_Boat,property_type_Camper/RV,property_type_Casa particular,property_type_Castle,...,property_type_Shared room in hotel,property_type_Shared room in loft,property_type_Shared room in rental unit,property_type_Shared room in townhouse,property_type_Shipping container,property_type_Tiny home,room_type_Entire home/apt,room_type_Hotel room,room_type_Private room,room_type_Shared room
13599,2,1.0,28,1125,6,0.17,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18991,5,3.0,1,730,12,0.24,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
19130,6,3.0,3,30,40,0.62,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10146,2,2.0,28,90,24,0.42,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8390,2,1.0,28,1125,0,0.00,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,2,2.0,28,365,0,0.00,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11964,4,2.0,1,120,48,5.35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5390,4,2.0,28,1125,15,0.29,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
860,4,2.0,28,1125,1,0.01,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
15795,2,1.0,28,1125,0,0.00,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Export X_train to Excel
X_train.to_excel("X_train.xlsx", index=False)

# Export y_train to Excel
y_train.to_frame().to_excel("y_train.xlsx", index=False)

In [ ]:
import shutil

# Define the source and destination paths for the Excel files
source_x_train = "X_train.xlsx"
source_y_train = "y_train.xlsx"
destination_drive = "/content/drive/My Drive/"

# Copy files to Google Drive
shutil.copy(source_x_train, destination_drive)
shutil.copy(source_y_train, destination_drive)

'/content/drive/My Drive/y_train.xlsx'

In [ ]:
# Merge X_train and y_train DataFrames
train_data = pd.concat([X_train, y_train], axis=1)

In [ ]:
# Export the merged DataFrame to Excel
train_data.to_excel("train_data.xlsx", index=False)

In [ ]:
import shutil

# Define the source and destination paths for the Excel file
source_file = "train_data.xlsx"
destination_drive = "/content/drive/My Drive/"

# Copy the file to Google Drive
shutil.copy(source_file, destination_drive)

'/content/drive/My Drive/train_data.xlsx'

In [ ]:
# Get all columns from the original dataset except the target column 'price'
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input1 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input1.update({
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 1,
    'maximum_nights': 1125,
    'number_of_reviews': 127,
    'reviews_per_month': 1.83,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df1 = pd.DataFrame([sample_input1])

# Make predictions using the trained model
predicted_price1 = model.predict(sample_input_df1)

print("Predicted price:", predicted_price1[0])

Predicted price: 72.22279821311538

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input2 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input2.update({
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 30,
    'number_of_reviews': 0,
    'reviews_per_month': 0,
    'property_type_Boat': 1,
    'room_type_Entire home/apt': 1
})

# Convert the sample input into a DataFrame
sample_input_df2 = pd.DataFrame([sample_input2])

# Make predictions using the trained model
predicted_price2 = model.predict(sample_input_df2)

print("Predicted price:", predicted_price2[0])

Predicted price: 277.50901636061155

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input3 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input3.update({
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 0,
    'reviews_per_month': 0,
    'property_type_Private room in townhouse': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df3 = pd.DataFrame([sample_input3])

# Make predictions using the trained model
predicted_price3 = model.predict(sample_input_df3)

print("Predicted price:", predicted_price3[0])

Predicted price: 80.89368038872418

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input4 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input4.update({
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 3,
    'reviews_per_month': 0.57,
    'property_type_Private room in bed and breakfast': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df4 = pd.DataFrame([sample_input4])

# Make predictions using the trained model
predicted_price4 = model.predict(sample_input_df4)

print("Predicted price:", predicted_price4[0])

Predicted price: 71.50411433173828

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input5 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input5.update({
    'accommodates': 3,
    'beds': 4,
    'minimum_nights': 1,
    'maximum_nights': 4,
    'number_of_reviews': 15,
    'reviews_per_month': 6.92,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df5 = pd.DataFrame([sample_input5])

# Make predictions using the trained model
predicted_price5 = model.predict(sample_input_df5)

print("Predicted price:", predicted_price4[0])

Predicted price: 71.50411433173828

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input6 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input6.update({
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 1,
    'maximum_nights': 35,
    'number_of_reviews': 3,
    'reviews_per_month': 0.49,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df6 = pd.DataFrame([sample_input6])

# Make predictions using the trained model
predicted_price6 = model.predict(sample_input_df6)

print("Predicted price:", predicted_price6[0])

Predicted price: 96.64684666417754

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input7 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input7.update({
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 1,
    'maximum_nights': 32,
    'number_of_reviews': 7,
    'reviews_per_month': 0.25,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df7 = pd.DataFrame([sample_input7])

# Make predictions using the trained model
predicted_price7 = model.predict(sample_input_df7)

print("Predicted price:", predicted_price7[0])

Predicted price: 96.21959763640962

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input8 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input8.update({
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 3,
    'reviews_per_month': 0.67,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df8 = pd.DataFrame([sample_input8])

# Make predictions using the trained model
predicted_price8 = model.predict(sample_input_df8)

print("Predicted price:", predicted_price8[0])

Predicted price: 93.48914493552842

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input9 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input9.update({
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 130,
    'number_of_reviews': 1,
    'reviews_per_month': 0.11,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df9 = pd.DataFrame([sample_input9])

# Make predictions using the trained model
predicted_price9 = model.predict(sample_input_df9)

print("Predicted price:", predicted_price9[0])

Predicted price: 92.42689886875506

In [ ]:
original_columns = list(X.columns)

# Initialize the sample input dictionary with zeros for all columns
sample_input10 = {col: 0 for col in original_columns}

# Update the sample input with the specific values you want to predict for
sample_input10.update({
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 1125,
    'number_of_reviews': 27,
    'reviews_per_month': 0.3,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
})

# Convert the sample input into a DataFrame
sample_input_df10 = pd.DataFrame([sample_input10])

# Make predictions using the trained model
predicted_price10 = model.predict(sample_input_df10)

print("Predicted price:", predicted_price10[0])

Predicted price: 70.92157342986675

In [ ]:
import pandas as pd

# Initialize lists to store inputs and predicted prices
input_data = []
predicted_prices = []

# Sample input data and predictions
samples = [
    {
        'accommodates': 1,
        'beds': 1,
        'minimum_nights': 1,
        'maximum_nights': 1125,
        'number_of_reviews': 127,
        'reviews_per_month': 1.83,
        'property_type_Private room in home': 1,
        'room_type_Private room': 1
    },
    {
        'accommodates': 2,
        'beds': 1,
        'minimum_nights': 28,
        'maximum_nights': 30,
        'number_of_reviews': 0,
        'reviews_per_month': 0,
        'property_type_Boat': 1,
        'room_type_Entire home/apt': 1
    },
    {
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 0,
    'reviews_per_month': 0,
    'property_type_Private room in townhouse': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 3,
    'reviews_per_month': 0.57,
    'property_type_Private room in bed and breakfast': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 3,
    'beds': 4,
    'minimum_nights': 1,
    'maximum_nights': 4,
    'number_of_reviews': 15,
    'reviews_per_month': 6.92,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 1,
    'maximum_nights': 35,
    'number_of_reviews': 3,
    'reviews_per_month': 0.49,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 1,
    'maximum_nights': 32,
    'number_of_reviews': 7,
    'reviews_per_month': 0.25,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 365,
    'number_of_reviews': 3,
    'reviews_per_month': 0.67,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 2,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 130,
    'number_of_reviews': 1,
    'reviews_per_month': 0.11,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
    },
    {
    'accommodates': 1,
    'beds': 1,
    'minimum_nights': 28,
    'maximum_nights': 1125,
    'number_of_reviews': 27,
    'reviews_per_month': 0.3,
    'property_type_Private room in home': 1,
    'room_type_Private room': 1
}
    # Add more sample inputs if needed
]

# Loop through each sample input, make predictions, and store the results
original_columns = list(X.columns)

# Loop through each sample input, make predictions, and store the results
for idx, sample in enumerate(samples, start=1):
    # Initialize the sample input dictionary with zeros for all columns
    sample_input = {col: 0 for col in original_columns}

    # Update the sample input with the specific values
    sample_input.update(sample)

    # Convert the sample input into a DataFrame
    sample_input_df = pd.DataFrame([sample_input])

    # Make predictions using the trained model
    predicted_price = model.predict(sample_input_df)

    # Append input data to the list
    input_data.append(sample)

    # Append predicted price to the list
    predicted_prices.append({'Predicted_price': predicted_price[0]})

# Create DataFrames for input data and predicted prices
input_df = pd.DataFrame(input_data)
predicted_prices_df = pd.DataFrame(predicted_prices)

# Print the input DataFrame
print("Input DataFrame:")
print(input_df)

# Print the predicted prices DataFrame
print("\nPredicted Prices DataFrame:")
print(predicted_prices_df)

Input DataFrame:
   accommodates  beds  minimum_nights  maximum_nights  number_of_reviews  \
0             1     1               1            1125                127
1             2     1              28              30                  0
2             1     1              28             365                  0
3             1     1              28             365                  3
4             3     4               1               4                 15
5             2     1               1              35                  3
6             2     1               1              32                  7
7             2     1              28             365                  3
8             2     1              28             130                  1
9             1     1              28            1125                 27

   reviews_per_month  property_type_Private room in home  \
0               1.83                                 1.0
1               0.00                                 NaN
2               0.00                                 NaN
3               0.57                                 NaN
4               6.92                                 1.0
5               0.49                                 1.0
6               0.25                                 1.0
7               0.67                                 1.0
8               0.11                                 1.0
9               0.30                                 1.0

   room_type_Private room  property_type_Boat  room_type_Entire home/apt  \
0                     1.0                 NaN                        NaN
1                     NaN                 1.0                        1.0
2                     1.0                 NaN                        NaN
3                     1.0                 NaN                        NaN
4                     1.0                 NaN                        NaN
5                     1.0                 NaN                        NaN
6                     1.0                 NaN                        NaN
7                     1.0                 NaN                        NaN
8                     1.0                 NaN                        NaN
9                     1.0                 NaN                        NaN

   property_type_Private room in townhouse  \
0                                      NaN
1                                      NaN
2                                      1.0
3                                      NaN
4                                      NaN
5                                      NaN
6                                      NaN
7                                      NaN
8                                      NaN
9                                      NaN

   property_type_Private room in bed and breakfast
0                                              NaN
1                                              NaN
2                                              NaN
3                                              1.0
4                                              NaN
5                                              NaN
6                                              NaN
7                                              NaN
8                                              NaN
9                                              NaN

Predicted Prices DataFrame:
   Predicted_price
0        72.222798
1       277.509016
2        80.893680
3        71.504114
4       156.720584
5        96.646847
6        96.219598
7        93.489145
8        92.426899
9        70.921573

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Define the file paths where you want to save the DataFrames in your Google Drive
input_df_path = "/content/drive/MyDrive/input_data.csv"
predicted_prices_df_path = "/content/drive/MyDrive/predicted_prices.csv"

# Merge the input DataFrame and predicted prices DataFrame using the index
result_df = pd.concat([input_df, predicted_prices_df], axis=1)

# Print the result DataFrame
print("Result DataFrame:")
print(result_df)

# Define the file path where you want to save the result DataFrame in your Google Drive
result_df_path = "/content/drive/MyDrive/input_and_predicted_prices.csv"

# Save the result DataFrame to Google Drive
result_df.to_csv(result_df_path, index=False)

print("DataFrames saved successfully.")

Result DataFrame:
   accommodates  beds  minimum_nights  maximum_nights  number_of_reviews  \
0             1     1               1            1125                127
1             2     1              28              30                  0
2             1     1              28             365                  0
3             1     1              28             365                  3
4             3     4               1               4                 15
5             2     1               1              35                  3
6             2     1               1              32                  7
7             2     1              28             365                  3
8             2     1              28             130                  1
9             1     1              28            1125                 27

   reviews_per_month  property_type_Private room in home  \
0               1.83                                 1.0
1               0.00                                 NaN
2               0.00                                 NaN
3               0.57                                 NaN
4               6.92                                 1.0
5               0.49                                 1.0
6               0.25                                 1.0
7               0.67                                 1.0
8               0.11                                 1.0
9               0.30                                 1.0

   room_type_Private room  property_type_Boat  room_type_Entire home/apt  \
0                     1.0                 NaN                        NaN
1                     NaN                 1.0                        1.0
2                     1.0                 NaN                        NaN
3                     1.0                 NaN                        NaN
4                     1.0                 NaN                        NaN
5                     1.0                 NaN                        NaN
6                     1.0                 NaN                        NaN
7                     1.0                 NaN                        NaN
8                     1.0                 NaN                        NaN
9                     1.0                 NaN                        NaN

   property_type_Private room in townhouse  \
0                                      NaN
1                                      NaN
2                                      1.0
3                                      NaN
4                                      NaN
5                                      NaN
6                                      NaN
7                                      NaN
8                                      NaN
9                                      NaN

   property_type_Private room in bed and breakfast  Predicted_price
0                                              NaN        72.222798
1                                              NaN       277.509016
2                                              NaN        80.893680
3                                              1.0        71.504114
4                                              NaN       156.720584
5                                              NaN        96.646847
6                                              NaN        96.219598
7                                              NaN        93.489145
8                                              NaN        92.426899
9                                              NaN        70.921573
DataFrames saved successfully.